# Generated by Django 3.2 on 2022-10-22 19:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utilities.models.abstract_user_profile


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('Core', '0006_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='division',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='postal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='thana',
        ),
        migrations.AddField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O +'), ('O-', 'O -'), ('A+', 'A +'), ('A-', 'A -'), ('B+', 'B +'), ('B-', 'B -'), ('AB+', 'AB +'), ('AB-', 'AB -')], max_length=3, null=True, verbose_name='Blood Group'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='joining_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Family/Last Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname'),
        ),
        migrations.AddField(
            model_name='profile',
            name='permanent_address',
            field=models.TextField(blank=True, help_text='Ex: 2/17, Mirpur-11', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='permanent_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_profile_permanent_district', to='address.district'),
        ),
        migrations.AddField(
            model_name='profile',
            name='permanent_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_profile_permanent_division', to='address.division'),
        ),
        migrations.AddField(
            model_name='profile',
            name='permanent_post_code',
            field=models.PositiveIntegerField(blank=True, help_text='Numeric 4 digits (ex: 1234)', null=True, validators=[django.core.validators.RegexValidator('^[\\d]{4}$', message='Numeric 4 digits (ex: 1234)')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='permanent_upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_profile_permanent_upazila', to='address.upazila'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[\\d]{10,12}$', message='Format (ex: 0123456789)')], verbose_name='Mobile Phone'),
        ),
        migrations.AddField(
            model_name='profile',
            name='present_address',
            field=models.TextField(blank=True, help_text='Ex: 2/17, Mirpur-11', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='present_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_profile_present_district', to='address.district'),
        ),
        migrations.AddField(
            model_name='profile',
            name='present_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_profile_present_division', to='address.division'),
        ),
        migrations.AddField(
            model_name='profile',
            name='present_post_code',
            field=models.PositiveIntegerField(blank=True, help_text='Numeric 4 digits (ex: 1234)', null=True, validators=[django.core.validators.RegexValidator('^[\\d]{4}$', message='Numeric 4 digits (ex: 1234)')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='present_upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_profile_present_upazila', to='address.upazila'),
        ),
        migrations.AddField(
            model_name='profile',
            name='same_as_present_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=utilities.models.abstract_user_profile.media_signature_path, verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utilities.models.abstract_user_profile.media_upload_path, verbose_name='Picture'),
        ),
    ]
